"""
Django settings for oae project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&t#5z1)f^l30wau)-n2nb8sl!&2&6&*g*l10i$8sw5z4lg=r69'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['37.143.8.48', 'www.exsum-test.ru', 'exsum-test.ru']


# Application definition

VENDOR_APPS = [
    #'admin_volt.apps.AdminVoltConfig',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'django_extensions',
    'import_export',
    'reversion',
    'reversion_compare',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

PROJECT_APPS = ['catalog',
                'operation',
                'dashboard',
                'tgbot']
INSTALLED_APPS = (VENDOR_APPS + PROJECT_APPS)

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'reversion.middleware.RevisionMiddleware'
]

ROOT_URLCONF = 'oae.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oae.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django',
        'USER': 'djangouser',
        'PASSWORD': 'Q3rfsTTrY42x',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
CSRF_TRUSTED_ORIGINS = ['https://exsum.ru', 'https://www.exsum.ru']

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Yekaterinburg'#'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=4*365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=4*365),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
SITE_URL = 'https://exsum-test.ru/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def badge_callback(request):
    return 3

UNFOLD = {
    "SITE_TITLE": "EXsum",
    "SITE_HEADER": "EXsum",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.png"),  # Укажи путь к своему фавикону
        },
    ],
    "SHOW_HISTORY": False,
    "SHOW_BACK_BUTTON": True,
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "ru": "🇷🇺",
            },
        },
    },

    "ICONS": {
        "oae.catalog": "settings ",
        "oae.operation": "article",
    },

    "COLORS": {
    "base": {
        "50": "249 250 251",
        "100": "243 244 246",
        "200": "229 231 235",
        "300": "209 213 219",
        "400": "156 163 175",
        "500": "107 114 128",
        "600": "75 85 99",
        "700": "55 65 81",
        "800": "31 41 55",
        "900": "17 24 39",
        "950": "3 7 18"
    },
    "primary": {
        "50": "236 253 245",  # #ECFDF5
        "100": "209 250 223",  # #D1FADF
        "200": "167 243 208",  # #A7F3D0
        "300": "110 231 183",  # #6EE7B7
        "400": "52 211 153",   # #34D399
        "500": "16 185 129",   # #10B981
        "600": "5 150 105",    # #059669
        "700": "4 120 87",     # #047857
        "800": "6 95 70",      # #065F46
        "900": "6 78 59",      # #064E3B
        "950": "6 78 34"       # #064E22
    }
},

    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": True,
        "navigation": [
            {
                # "title": "Операции",
                "icon": "equal",
                "collapsible": False,
                "items": [

                    {
                        "title": "Сделки",
                        "icon": "contract",
                        "link": reverse_lazy("admin:operation_deal_changelist"),
                    },
                ],
            },
{
                "icon": "graphic",
                "collapsible": False,
                "items": [

                    {
                        "title": "Графики",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:dashboard_histogram_changelist"),
                    },
                ],
            },
            {
                "icon": "table",
                "collapsible": False,
                "items": [

                    {
                        "title": "Аналитика",
                        "icon": "table",
                        "link": reverse_lazy("admin:analytics_view"),
                    },
                ],
            },
{
                "icon": "report",
                "collapsible": False,
                "items": [

                    {
                        "title": "Отчет",
                        "icon": "report",
                        "link": reverse_lazy("admin:report_view"),
                    },
                ],
            },
            {
                "icon": "percent",
                "collapsible": False,
                "items": [

                    {
                        "title": "Процент",
                        "icon": "percent",
                        "link": reverse_lazy("admin:operation_percentcourse_changelist"),
                    },
                ],
            },

            #{
                #"title": 'Навигация',
                #"separator": True,  # Top border
                #"collapsible": False,  # Collapsible group of links
                #"items": [
                    #{
                        #"title": "Дашбоард",
                        #"icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        #"link": reverse_lazy("admin:index"),
                        #"badge": badge_callback,
                        #"permission": lambda request: request.user.is_superuser,
                    #},
                #],
            #},

             {
                "title": "Каталог",
                "icon": "settings",
                "collapsible": False,
                "items": [
                    {
                        "title": "Валюты",
                        "icon": "attach_money",
                        "link": reverse_lazy("admin:catalog_currency_changelist"),
                    },
                    {
                        "title": "ДДС",
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:catalog_cashflow_changelist"),
                    },
                    {
                        "title": "Контрагенты",
                        "icon": "person",
                        "link": reverse_lazy("admin:catalog_contractor_changelist"),
                    },
                    {
                        "title": "Счета",
                        "icon": "local_mall",
                        "link": reverse_lazy("admin:catalog_bill_changelist"),
                    },
                    {
                        "title": "Категории",
                        "icon": "category",
                        "link": reverse_lazy("admin:catalog_category_changelist"),
                    },
                ],
            },


        ],
    },
}

CACHE_MIDDLEWARE_KEY_PREFIX = 'site'
CACHE_MIDDLEWARE_SECONDS = 0


# Celery
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}  # 1 hour.
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# Telegram
TELEGRAM_TOKEN = '7765932977:AAFBgdMZ-j6EXqDW6o1vyxC3zogJXs0hJgE'
#STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

