# Generated by Django 5.1.7 on 2026-02-20 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Краткое наименование')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('remainder', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Остаток')),
                ('initial_remainder', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Первоначальный остаток')),
                ('rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс')),
                ('initial_rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Первоначальный курс')),
                ('old_rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Старый курс')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'catalog_bills',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('type_cf', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='income', max_length=20, verbose_name='Тип ДДС')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'ДДС',
                'verbose_name_plural': 'ДДС',
                'db_table': 'catalog_cashflows',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'catalog_categorys',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('duty', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'catalog_contractors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Краткое наименование')),
                ('zeros_after', models.IntegerField(default=2, verbose_name='Нолей после запятой')),
                ('zeros_after_rate', models.IntegerField(default=2, verbose_name='Курс, нолей после запятой')),
                ('rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'catalog_currencys',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Долг')),
                ('duty_cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Долг себестоимости')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_history', to='catalog.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'История контрагента',
                'verbose_name_plural': 'История контрагентов',
                'db_table': 'catalog_contractors_history',
                'ordering': ['id'],
            },
        ),
    ]
