# Generated by Django 5.1.7 on 2026-02-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorhistory',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_deal', to='operation.deal', verbose_name='Сделка'),
        ),
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_bills', to='catalog.currency', verbose_name='Валюта'),
        ),
    ]
