# Generated by Django 5.1.7 on 2026-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contractor_duty_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='duty_usdt',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Долг USDT'),
        ),
    ]
