# Generated by Django 5.1.7 on 2026-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_contractor_duty_usdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorhistory',
            name='duty_usdt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Долг USDT'),
        ),
    ]
