# Generated by Django 5.1.7 on 2026-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contractorhistory_duty_usdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='duty',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='duty_usdt',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Баланс USDT'),
        ),
        migrations.AlterField(
            model_name='contractorhistory',
            name='duty',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='contractorhistory',
            name='duty_cost',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Баланс себестоимости'),
        ),
        migrations.AlterField(
            model_name='contractorhistory',
            name='duty_usdt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Баланс USDT'),
        ),
    ]
