# Generated by Django 5.1.7 on 2026-02-20 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1024, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'db_table': 'operation_logs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PercentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Процент',
                'verbose_name_plural': 'Проценты',
                'db_table': 'operation_percent',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carvet_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Id внешний')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('rate', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='Курс')),
                ('old_bill_rate', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='Старый курс')),
                ('old_bill_remainder', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Старый остаток')),
                ('calculated', models.BooleanField(default=False, verbose_name='Рассчитано')),
                ('closed', models.BooleanField(default=False, verbose_name='Закончена')),
                ('comment', models.CharField(blank=True, max_length=2056, null=True, verbose_name='Комментарий')),
                ('duty_deal', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, verbose_name='Долг')),
                ('national_currency', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Нац.валюта')),
                ('deal_1c', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Заказ 1с')),
                ('by_nikita', models.BooleanField(default=False, verbose_name='Никита')),
                ('by_ie', models.BooleanField(default=False, verbose_name='ИП')),
                ('amount_repaid', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Погашено')),
                ('is_repaid', models.BooleanField(default=False, verbose_name='Погашено полностью')),
                ('status_ie', models.IntegerField(choices=[(0, 'Не ип'), (1, 'Долг'), (2, 'Рассчет'), (3, 'Начальный долг')], default=0, verbose_name='Статус рассчета')),
                ('cashflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_cashflow', to='catalog.cashflow', verbose_name='ДДС')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_category', to='catalog.category', verbose_name='Категория')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_contractor', to='catalog.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'operation_deals',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_old', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс до')),
                ('rate_new', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс после')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_course', to='operation.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Изменение курса',
                'verbose_name_plural': 'Изменение курсов',
                'db_table': 'operation_deal_course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Сумма прихода')),
                ('income_rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс прихода')),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Сумма расхода')),
                ('expense_rate', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Курс расхода')),
                ('calculated', models.BooleanField(default=False, verbose_name='Рассчитано')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('commission', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, verbose_name='Комиссия')),
                ('rate_calculated', models.BooleanField(default=False, verbose_name='Рассчитан приход')),
                ('transaction_id', models.CharField(blank=True, max_length=2056, null=True, verbose_name='Hash')),
                ('date_upload', models.DateField(auto_now_add=True, null=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_data', to='operation.deal', verbose_name='Сделка')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_expense', to='catalog.bill', verbose_name='Счет расхода')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_income', to='catalog.bill', verbose_name='Счет прихода')),
            ],
            options={
                'verbose_name': 'Приход/Расход',
                'verbose_name_plural': 'Приходы/Расходы',
                'db_table': 'operation_deal_in_ex',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_before', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Приход до')),
                ('income_after', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Приход после')),
                ('expense_before', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Расход до')),
                ('expense_after', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=18, null=True, verbose_name='Расход после')),
                ('in_ex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_ex_history', to='operation.incomeexpense', verbose_name='Пара')),
            ],
            options={
                'verbose_name': 'История балансов',
                'verbose_name_plural': 'Истории балансов',
                'db_table': 'operation_in_ex_history',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_duty', models.BooleanField(default=False, verbose_name='По долгу контрагента')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Сумма погашения')),
                ('date_create', models.DateTimeField()),
                ('calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_duties', to='operation.deal', verbose_name='Расчёт')),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='operation.deal', verbose_name='Долг')),
            ],
            options={
                'unique_together': {('duty', 'calc')},
            },
        ),
    ]
