# Generated by Django 5.1.7 on 2026-02-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_contractor_duty_usdt'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='expense_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_contractor', to='catalog.contractor', verbose_name='Контрагент прихода'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='income_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_contractor', to='catalog.contractor', verbose_name='Контрагент прихода'),
        ),
    ]
