# Generated by Django 5.1.7 on 2026-02-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_incomeexpense_expense_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpense',
            name='expense_contractor',
        ),
        migrations.RemoveField(
            model_name='incomeexpense',
            name='income_contractor',
        ),
    ]
