# Generated by Django 5.1.7 on 2026-02-23 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contractorhistory_duty_usdt'),
        ('operation', '0003_remove_incomeexpense_expense_contractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorDebtOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Сумма операции')),
                ('percent', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, verbose_name='Процент')),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_operations', to='catalog.contractor')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.currency', verbose_name='Валюта')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_operations', to='operation.deal')),
            ],
        ),
    ]
