# Generated by Django 5.1.7 on 2026-02-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_contractordebtoperation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractordebtoperation',
            options={'ordering': ['id'], 'verbose_name': 'Движения контрагентов', 'verbose_name_plural': 'Движения контрагентов'},
        ),
        migrations.AlterModelTable(
            name='contractordebtoperation',
            table='operation_contractor_debt',
        ),
    ]
