# Generated by Django 5.1.7 on 2026-02-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contractorhistory_duty_usdt'),
        ('operation', '0005_alter_contractordebtoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordebtoperation',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contractordebtoperation',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_operations', to='catalog.contractor', verbose_name='Контрагент'),
        ),
    ]
