# Generated by Django 5.1.7 on 2026-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_alter_contractordebtoperation_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='rate_contractors',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='Курс контрагентов'),
        ),
    ]
