# Generated by Django 5.1.7 on 2026-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_contractordebtoperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordebtoperation',
            name='operation_type',
            field=models.CharField(choices=[('write_off', 'Списание -'), ('write_on', 'Зачисление +')], default='write_off', max_length=20, verbose_name='Тип операции'),
        ),
    ]
