# Generated by Django 5.1.7 on 2026-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_contractordebtoperation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='rate_contractors',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='Курс момента'),
        ),
    ]
