# Generated by Django 5.1.7 on 2026-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_alter_deal_rate_contractors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='old_bill_rate',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=10, null=True, verbose_name='Старый курс'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='old_bill_remainder',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, verbose_name='Старый остаток'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=10, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='rate_contractors',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=10, null=True, verbose_name='Курс момента'),
        ),
    ]
