# Generated by Django 5.1.7 on 2026-03-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_contractor_duty_alter_contractor_duty_usdt_and_more'),
        ('operation', '0011_alter_deal_old_bill_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.FloatField(blank=True, null=True, verbose_name='Новое значение')),
                ('new_value', models.FloatField(blank=True, null=True, verbose_name='Старое значение')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'История курса',
                'verbose_name_plural': 'История курсов',
                'db_table': 'operation_course_history',
                'ordering': ['id'],
            },
        ),
    ]
