# Generated by Django 5.1.7 on 2026-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_coursehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='rate_conversion',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=10, null=True, verbose_name='Курс конвертации'),
        ),
    ]
